# https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html

version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18.x

  pre_build:
    commands:
      - npm ci

artifacts:
  files:
    - '**/*'
  exclude-paths:
    - './node_modules/**/*'
    - '**/.*/**/*'
